-- ============================================
-- MOA OTT 구독 공유 서비스 DB
-- Version 5.1
-- DDL ONLY (CREATE TABLE + FK + INDEX)
-- 총 27개 테이블
-- ============================================

SET FOREIGN_KEY_CHECKS = 0;

-- ============================================
-- 1. DROP
-- ============================================

DROP TABLE IF EXISTS SETTLEMENT_RETRY_HISTORY;
DROP TABLE IF EXISTS REFUND_RETRY_HISTORY;
DROP TABLE IF EXISTS PAYMENT_RETRY_HISTORY;
DROP TABLE IF EXISTS TRANSFER_TRANSACTION;
DROP TABLE IF EXISTS SETTLEMENT;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS DEPOSIT;
DROP TABLE IF EXISTS PARTY_MEMBER;
DROP TABLE IF EXISTS PARTY;
DROP TABLE IF EXISTS USER_CARD;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PUSH;
DROP TABLE IF EXISTS PUSH_CODE;
DROP TABLE IF EXISTS COMMUNITY;
DROP TABLE IF EXISTS COMMUNITY_CODE;
DROP TABLE IF EXISTS CHATBOT_KNOWLEDGE;
DROP TABLE IF EXISTS LOGIN_HISTORY;
DROP TABLE IF EXISTS USER_OTP_BACKUP_CODE;
DROP TABLE IF EXISTS BLACKLIST;
DROP TABLE IF EXISTS OAUTH_ACCOUNT;
DROP TABLE IF EXISTS EMAIL_VERIFICATION;
DROP TABLE IF EXISTS ACCOUNT_VERIFICATION;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BANK_CODE;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- 2. CREATE TABLE
-- ============================================

CREATE TABLE BANK_CODE (
    BANK_CODE VARCHAR(10) PRIMARY KEY,
    BANK_NAME VARCHAR(50) NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USERS (
    USER_ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(255),
    NICKNAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(14),
    PROFILE_IMAGE VARCHAR(255),
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    USER_STATUS VARCHAR(20) NOT NULL,
    REG_DATE DATETIME NOT NULL,
    CI VARCHAR(100),
    PASS_CERTIFIED_AT DATETIME,
    LAST_LOGIN_DATE DATETIME,
    LOGIN_FAIL_COUNT INT DEFAULT 0,
    UNLOCK_SCHEDULED_AT DATETIME,
    DELETE_DATE DATETIME,
    DELETE_TYPE VARCHAR(20),
    DELETE_DETAIL VARCHAR(500),
    AGREE_MARKETING BOOLEAN NOT NULL DEFAULT 0,
    EMAIL_VERIFICATION_TOKEN VARCHAR(200),
    EMAIL_VERIFIED_AT DATETIME,
    RESET_TOKEN VARCHAR(200),
    PROVIDER VARCHAR(50),
    OTP_SECRET VARCHAR(64),
    OTP_ENABLED TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY UQ_USERS_CI (CI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ACCOUNT_VERIFICATION (
    VERIFICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    BANK_TRAN_ID VARCHAR(30) NOT NULL,
    BANK_CODE VARCHAR(10) NOT NULL,
    ACCOUNT_NUM VARCHAR(20) NOT NULL,
    ACCOUNT_HOLDER VARCHAR(50) NOT NULL,
    VERIFY_CODE VARCHAR(4) NOT NULL,
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    EXPIRED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_VERIFICATION_BANK_TRAN (BANK_TRAN_ID),
    INDEX IDX_VERIFICATION_USER_STATUS (USER_ID, STATUS),
    INDEX IDX_VERIFICATION_EXPIRED (STATUS, EXPIRED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE OAUTH_ACCOUNT (
    OAUTH_ID VARCHAR(255) PRIMARY KEY,
    PROVIDER VARCHAR(20) NOT NULL,
    PROVIDER_USER_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    CONNECTED_DATE DATETIME NOT NULL,
    RELEASE_DATE DATETIME,
    UNIQUE KEY UQ_OAUTH_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
    UNIQUE KEY UQ_OAUTH_USER_PROVIDER (USER_ID, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BLACKLIST (
    BLACKLIST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    REASON VARCHAR(500),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    REG_DATE DATE NOT NULL,
    RELEASE_DATE DATE,
    ACTIVE_USER_ID VARCHAR(50) GENERATED ALWAYS AS (
        CASE WHEN STATUS = 'ACTIVE' THEN USER_ID ELSE NULL END
    ) VIRTUAL,
    UNIQUE KEY UQ_BLACKLIST_ACTIVE_USER (ACTIVE_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EMAIL_VERIFICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    TOKEN VARCHAR(100) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    VERIFIED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_EMAIL_VERIFICATION_TOKEN (TOKEN),
    KEY IDX_EMAIL_VERIFICATION_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LOGIN_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    LOGIN_AT DATETIME NOT NULL,
    SUCCESS TINYINT(1) NOT NULL,
    LOGIN_IP VARCHAR(45),
    USER_AGENT VARCHAR(255),
    FAIL_REASON VARCHAR(255),
    LOGIN_TYPE VARCHAR(50),
    INDEX IDX_LOGIN_HISTORY_USER_AT (USER_ID, LOGIN_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USER_OTP_BACKUP_CODE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    CODE_HASH VARCHAR(255) NOT NULL,
    USED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USED_AT DATETIME,
    UNIQUE KEY UQ_USER_CODE (USER_ID, CODE_HASH),
    INDEX IDX_OTP_BACKUP_USER (USER_ID),
    INDEX IDX_OTP_BACKUP_USED (USER_ID, USED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CHATBOT_KNOWLEDGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(50) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    QUESTION VARCHAR(500) NOT NULL,
    ANSWER TEXT NOT NULL,
    KEYWORDS VARCHAR(500),
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    EMBEDDING JSON
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMMUNITY_CODE (
    COMMUNITY_CODE_ID INT PRIMARY KEY,
    CATEGORY VARCHAR(20) NOT NULL,
    CODE_NAME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMMUNITY (
    COMMUNITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    COMMUNITY_CODE_ID INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VIEW_COUNT INT DEFAULT 0,
    FILE_ORIGINAL VARCHAR(255),
    FILE_UUID VARCHAR(255),
    ANSWER_CONTENT VARCHAR(500),
    ANSWERED_AT DATETIME,
    ANSWER_STATUS VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PUSH_CODE (
    PUSH_CODE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE_NAME VARCHAR(50) NOT NULL,
    TITLE_TEMPLATE VARCHAR(200) NOT NULL,
    CONTENT_TEMPLATE VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PUSH (
    PUSH_ID INT AUTO_INCREMENT PRIMARY KEY,
    RECEIVER_ID VARCHAR(50) NOT NULL,
    PUSH_CODE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    MODULE_ID VARCHAR(50),
    MODULE_TYPE VARCHAR(50),
    SENT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    READ_AT DATETIME,
    IS_READ CHAR(1) NOT NULL DEFAULT 'N',
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    PRICE INT NOT NULL,
    MAX_SHARE INT,
    IMAGE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    SUBSCRIPTION_STATUS VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    CANCEL_REASON VARCHAR(255),
    CANCEL_DATE DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    BANK_CODE VARCHAR(10) NOT NULL,
    BANK_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    ACCOUNT_HOLDER VARCHAR(50) NOT NULL,
    IS_VERIFIED CHAR(1) NOT NULL DEFAULT 'N',
    FINTECH_USE_NUM VARCHAR(30),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VERIFY_DATE DATETIME,
    UNIQUE KEY UQ_ACCOUNT_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USER_CARD (
    USER_ID VARCHAR(50) PRIMARY KEY,
    BILLING_KEY VARCHAR(255) NOT NULL,
    CARD_COMPANY VARCHAR(50) NOT NULL,
    CARD_NUMBER VARCHAR(20) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PARTY (
    PARTY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    PARTY_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    MAX_MEMBERS INT NOT NULL,
    CURRENT_MEMBERS INT NOT NULL DEFAULT 1,
    MONTHLY_FEE INT NOT NULL,
    OTT_ID VARCHAR(100),
    OTT_PASSWORD VARCHAR(255),
    ACCOUNT_ID INT,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PARTY_MEMBER (
    PARTY_MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTY_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    MEMBER_ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    MEMBER_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    JOIN_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WITHDRAW_DATE DATETIME,
    UNIQUE KEY UQ_PARTY_MEMBER_USER (PARTY_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DEPOSIT (
    DEPOSIT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    DEPOSIT_TYPE VARCHAR(20) NOT NULL DEFAULT 'SECURITY',
    DEPOSIT_AMOUNT INT NOT NULL,
    DEPOSIT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PAYMENT_DATE DATETIME NOT NULL,
    REFUND_DATE DATETIME,
    REFUND_AMOUNT INT,
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOSS_PAYMENT_KEY VARCHAR(255),
    ORDER_ID VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PAYMENT (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    PAYMENT_AMOUNT INT NOT NULL,
    PAYMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PAYMENT_METHOD VARCHAR(20) NOT NULL DEFAULT 'CARD',
    PAYMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOSS_PAYMENT_KEY VARCHAR(255),
    ORDER_ID VARCHAR(100),
    CARD_NUMBER VARCHAR(20),
    CARD_COMPANY VARCHAR(50),
    TARGET_MONTH VARCHAR(7) NOT NULL,
    SETTLEMENT_ID INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PAYMENT_RETRY_HISTORY (
    RETRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_ID INT NOT NULL,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    ATTEMPT_NUMBER INT NOT NULL,
    ATTEMPT_DATE DATETIME NOT NULL,
    RETRY_REASON VARCHAR(500),
    RETRY_STATUS VARCHAR(20) NOT NULL,
    NEXT_RETRY_DATE DATETIME,
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE REFUND_RETRY_HISTORY (
    RETRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPOSIT_ID INT NOT NULL,
    TOSS_PAYMENT_KEY VARCHAR(255),
    ATTEMPT_NUMBER INT NOT NULL DEFAULT 1,
    ATTEMPT_DATE DATETIME NOT NULL,
    RETRY_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    RETRY_TYPE VARCHAR(20) NOT NULL DEFAULT 'REFUND',
    NEXT_RETRY_DATE DATETIME,
    REFUND_AMOUNT INT,
    REFUND_REASON VARCHAR(200),
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SETTLEMENT (
    SETTLEMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTY_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID INT,
    SETTLEMENT_MONTH VARCHAR(7) NOT NULL,
    SETTLEMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    TOTAL_AMOUNT INT NOT NULL,
    COMMISSION_RATE DECIMAL(3,2) NOT NULL DEFAULT 0.15,
    COMMISSION_AMOUNT INT NOT NULL,
    NET_AMOUNT INT NOT NULL,
    SETTLEMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SETTLEMENT_DATE DATETIME,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    BANK_TRAN_ID VARCHAR(30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TRANSFER_TRANSACTION (
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SETTLEMENT_ID INT NOT NULL,
    BANK_TRAN_ID VARCHAR(30),
    FINTECH_USE_NUM VARCHAR(30) NOT NULL,
    TRAN_AMT INT NOT NULL,
    PRINT_CONTENT VARCHAR(20),
    REQ_CLIENT_NAME VARCHAR(20),
    RSP_CODE VARCHAR(10),
    RSP_MESSAGE VARCHAR(100),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SETTLEMENT_RETRY_HISTORY (
    RETRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    SETTLEMENT_ID INT NOT NULL,
    ATTEMPT_NUMBER INT NOT NULL,
    ATTEMPT_DATE DATETIME NOT NULL,
    RETRY_REASON VARCHAR(500),
    RETRY_STATUS VARCHAR(20) NOT NULL,
    NEXT_RETRY_DATE DATETIME,
    TRANSFER_AMOUNT INT NOT NULL,
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    BANK_RSP_CODE VARCHAR(10),
    BANK_RSP_MESSAGE VARCHAR(200),
    BANK_TRAN_ID VARCHAR(30),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- 3. INDEX
-- ============================================

ALTER TABLE CHATBOT_KNOWLEDGE
ADD FULLTEXT INDEX FT_CHATBOT (QUESTION, ANSWER, KEYWORDS);

-- ============================================
-- 4. FOREIGN KEY
-- ============================================

ALTER TABLE ACCOUNT ADD FOREIGN KEY (BANK_CODE) REFERENCES BANK_CODE(BANK_CODE);
ALTER TABLE ACCOUNT_VERIFICATION ADD FOREIGN KEY (BANK_CODE) REFERENCES BANK_CODE(BANK_CODE);

ALTER TABLE OAUTH_ACCOUNT ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE BLACKLIST ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE EMAIL_VERIFICATION ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE LOGIN_HISTORY ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE USER_OTP_BACKUP_CODE ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;

ALTER TABLE COMMUNITY ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE COMMUNITY ADD FOREIGN KEY (COMMUNITY_CODE_ID) REFERENCES COMMUNITY_CODE(COMMUNITY_CODE_ID);
ALTER TABLE PUSH ADD FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PRODUCT ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);
ALTER TABLE SUBSCRIPTION ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE SUBSCRIPTION ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE ACCOUNT ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE USER_CARD ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PARTY ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE PARTY ADD FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE PARTY ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE PARTY_MEMBER ADD FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);
ALTER TABLE PARTY_MEMBER ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE DEPOSIT ADD FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);
ALTER TABLE DEPOSIT ADD FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID);
ALTER TABLE DEPOSIT ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PAYMENT ADD FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE SETTLEMENT ADD FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);
ALTER TABLE SETTLEMENT ADD FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE SETTLEMENT ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE TRANSFER_TRANSACTION ADD FOREIGN KEY (SETTLEMENT_ID) REFERENCES SETTLEMENT(SETTLEMENT_ID);
ALTER TABLE SETTLEMENT_RETRY_HISTORY ADD FOREIGN KEY (SETTLEMENT_ID) REFERENCES SETTLEMENT(SETTLEMENT_ID);

SET FOREIGN_KEY_CHECKS = 1;
